services:
  localdb:
      image: mcr.microsoft.com/mssql/server:2022-latest
      container_name: localdb
      environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Dani2002
      ports:
        - "1433:1433"