db:
  image: takacsdanii/bevdevops-mssql-db:latest
  password: "ProdDbPassword2025!"
  replicaCount: 1

backend:
  image: takacsdanii/bevdevops-backend
  tag: latest
  replicaCount: 2
  environment: "Production"

frontend:
  image: takacsdanii/bevdevops-frontend-prod
  tag: latest
  replicaCount: 2
  environment: "Production"