db:
  image: takacsdanii/bevdevops-mssql-db:latest
  password: "proddbpassword"
  replicaCount: 1

backend:
  image: takacsdanii/bevdevops-backend
  tag: v1.0.1
  replicaCount: 2
  environment: "Production"

frontend:
  image: takacsdanii/bevdevops-frontend-prod
  tag: v1.0.1
  replicaCount: 2
  environment: "Production"