global:
  appHost: "localhost"

db:
  image: takacsdanii/bevdevops-mssql-db:latest
  password: "devdbpassword"
  replicaCount: 1

backend:
  image: takacsdanii/bevdevops-backend
  tag: latest
  replicaCount: 2
  environment: "Development"

frontend:
  image: takacsdanii/bevdevops-frontend-dev
  tag: latest
  replicaCount: 2
  environment: "Development"