apiVersion: v1
kind: Service
metadata:
  name: bevdevops-backend-{{ .Release.Name }}
spec:
  selector:
    app: bevdevops-backend-server-{{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 8080
      nodePort: {{ if eq .Values.backend.environment "Production" }}8090{{ else }}8088{{ end }}
  type: NodePort