apiVersion: v1
kind: Service
metadata:
  name: bevdevops-db-{{ .Release.Name }}
spec:
  selector:
    app: bevdevops-db-server-{{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433