apiVersion: v1
kind: Service
metadata:
  name: bevdevops-frontend-{{ .Release.Name }}
spec:
  selector:
    app: bevdevops-frontend-server-{{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort