apiVersion: apps/v1
kind: Deployment
metadata:
  name: bevdevops-frontend-{{ .Release.Name }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: bevdevops-frontend-server-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: bevdevops-frontend-server-{{ .Release.Name }}
    spec:
      containers:
      - name: bevdevops-frontend-container-{{ .Release.Name }}
        image: "{{ .Values.frontend.image }}:{{ .Values.frontend.tag }}"
        ports:
        - containerPort: 80